default: &default
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: db/ruby_levenshtein_example_development

test:
  <<: *default
  database: db/ruby_levenshtein_example_test

production:
  <<: *default
  database: db/ruby_levenshtein_example_production
