# Scheduler
:dynamic: true
:concurrency: 128
:pool: 25
development:
  :verbose: false
  :pidfile: ./tmp/pids/sidekiq.pid
  :logfile: ./log/sidekiq.log
staging:
  :verbose: false
  :pidfile: ./tmp/pids/sidekiq.pid
  :logfile: ./log/sidekiq.log
production:
  :verbose: false
  :pidfile: ./tmp/pids/sidekiq.pid
  :logfile: ./log/sidekiq.log
#queue weighting is defined in the systemd configs for the workers on the server
:queues:
  - ["critical", 10]
  - ["high", 7]
  - ["medium", 5]
  - ["low", 1]
