# Scheduler
:dynamic: true
:concurrency: 32
:pool: 25
development:
  :verbose: false
  :pidfile: ./tmp/pids/sidekiq.pid
  :logfile: ./log/sidekiq.log
  :concurrency:  32
staging:
  :verbose: false
  :pidfile: ./tmp/pids/sidekiq.pid
  :logfile: ./log/sidekiq.log
  :concurrency:  10
production:
  :verbose: false
  :pidfile: ./tmp/pids/sidekiq.pid
  :logfile: ./log/sidekiq.log
  :concurrency:  10
#queue weighting is defined in the systemd configs for the workers on the server
:queues:
  - ["critical", 10]
  - ["high", 7]
  - ["medium", 5]
  - ["low", 1]
